### ISSUE TITLE
Generalize DTF decoding methods to accept arbitrary in-memory buffers

### ISSUE THREAD

**Issue by Ameobea** [fat-whale/tectonicdb#11]
Current methods only work for reading from Files.  The ability to read from any random `Vec<u8>` should be added, ideally in a way that generalizes the existing methods rather than adding new ones.

**Comment by 0b01** [comment]
Added a function to read from a buffer slice.

https://github.com/rickyhan/tectonicdb/commit/73c5b6c6185b14bcc6aa912f9e1a55a2d344d7a7
