### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by Ameobea** [fat-whale/tectonicdb#2]
There are currently several tests that don't pass.  The reasons are difficult to discren; the test output is in many cases hundreds of lines long.

In addition, there are potential instances of dependencies between tests.  A test file is created by one test (which is called directly by a different test rather than getting invoked by the Rust test manager) and is read by another test that expects it to be in a certain state and contain data from the first test.  This may the source of at least some of the issues.

**Comment by 0b01** [comment]
In your bashrc:

```bash
export RUST_TEST_THREADS=1
```

This runs tests sequentially.

**Comment by Ameobea** [comment]
Ahh, I see.  I'll set that on the CI.  Would be awesome to add that to the docs for the project somewhere.

**Comment by Ameobea** [comment]
@rickyhan is there any configuration required for the google drive storage test?  Some kind of bucket name that needs to be put in the environment or something?  Getting an authorization error while attempting to upload to Google Cloud Storage.

**Comment by Ameobea** [comment]
Lol, disregard that; It's pulling from my own environment variable config.  Sorry; forgot about how I had that set up.
